imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ MopaBootstrapBundle , VBWebBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        is_bundle: false


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: VB\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
    from_email:
        address:        no-reply@virgosbeauty.com
        sender_name:    Virgos Beauty
    profile:
        form:
            type: vb_user_profile

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default
        horizontal:           false
        render_optional_text:  false
    initializr:
        meta:
#            title:        "YYY"
#            description:  "This is test site"
#            keywords:     "keyword1,keyword 2"
#            author_name:  "this is me"
#            author_url:   "/human.txt"
            nofollow:     false
            noindex:      false
        dns_prefetch:
              - '//ajax.googleapis.com'
        google:
#            wt: 'xxx'
            analytics: 'UA-47734275-2'

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true

white_october_breadcrumbs:
    separator: ''

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['html_purifier']
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source','-','Save','-','Templates']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image','Flash','Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize', 'ShowBlocks']
    ui_color: '#000000'
    startup_outline_blocks: true
    width: 100% #Integer or %
    height: 300 #Integer or %
    language: 'en-au'
#    filebrowser_upload_url:
#        url: relative-url.php?type=file
#    filebrowser_image_browse_url:
#        route: route_name
#        route_parameters:
#            type: image

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        product_image:
            uri_prefix: /images/product
            upload_destination: product_image_fs
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            namer: vich_uploader.namer_uniqid

knp_gaufrette:
    adapters:
        product_image_adapter:
            local:
                directory: %kernel.root_dir%/../web/images/public/product_image

    filesystems:
        product_image_fs:
            adapter:    product_image_adapter

    stream_wrapper:
        protocol: ~

liip_imagine:
    driver: gd
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: images/cache
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web
    cache: default
    data_loader: default
    controller_action:    liip_imagine.controller:filterAction
    filter_sets:
        cache: ~
        product_image_list_item:
            filters:
                thumbnail: {size: [250, 250], mode: inset }
        product_image_slideshow:
            filters:
                thumbnail: {size: [400, 400], mode: inset }
        product_image_slideshow_thumb:
            filters:
                thumbnail: {size: [100, 100], mode: outbound }

hwi_oauth:
    connect:
        account_connector: vb_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "email,publish_actions"
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

gregwar_captcha:
    background_color: [255,255,255]
    quality: 50

sonata_seo:
    encoding: UTF-8
    page:
        title: Virgos beauty | Sản phẩm làm đẹp và chăm sóc sức khoẻ từ Úc
        metas:
            name:
                keywords:  >
                    kem nhau thai cuu, kem duong da, phan trang diem, son moi, thuc pham thuc an, san pham tu uc
                description:   >
                    Virgos beauty cung cấp sản phẩm làm đẹp, chăm sóc sức khoẻ từ Úc. Sản phẩm làm đẹp chính gồm
                     có kem nhau thai cừu, mỹ phẩm từ cac hãng nổi tiếng. Sản phẩm chăm sóc sức khoẻ chính gồm có thực
                     phẩm chưc năng như hạt chia, các vitamin và dưỡng chất cần thiết dành cho mọi lứa tuổi.
                robots:               index, follow
            property:
                'og:site_name':       VirgosBeauty.com
                'og:description':     Sản phẩm làm đẹp và chăm sóc sức khoẻ từ Úc
                'og:title':           VirgosBeauty.com
                'og:url':             http://virgosbeauty.com
            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            'prefix':   og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# product: http://ogp.me/ns/product#
