services:
    sonata.admin.product_category:
        class: VB\CommerceBundle\Admin\ProductCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "commerce", label: "Product category" }
        arguments:
            - ~
            - VB\CommerceBundle\Entity\ProductCategory
            - ~
    sonata.admin.product:
        class: VB\CommerceBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "commerce", label: "Product" }
        arguments:
            - ~
            - VB\CommerceBundle\Entity\Product
            - ~
    sonata.admin.product_request:
        class: VB\CommerceBundle\Admin\ProductRequestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "commerce", label: "Product request" }
        arguments:
            - ~
            - VB\CommerceBundle\Entity\ProductRequest
            - ~
    sonata.admin.shipment:
        class: VB\CommerceBundle\Admin\ShipmentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "commerce", label: "Shipment" }
        arguments:
            - ~
            - VB\CommerceBundle\Entity\Shipment
            - VBCommerceBundle:ShipmentCRUD
    sonata.admin.shipment_item:
        class: VB\CommerceBundle\Admin\ShipmentItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "commerce", label: "ShipmentItem", show_in_dashboard: false }
        arguments:
            - ~
            - VB\CommerceBundle\Entity\ShipmentItem
            - ~
        calls:
            - [ setDoctrine, [ @doctrine ]]